#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, random, zlib
from datetime import datetime

DATA_SIZE = 1375

class Sender:
    """
    Class representing the Sender in a Transport Protocol.
    """

    def __init__(self, host, port):
        """
        Initializes Sender.
        Args:
            host - str host to connect to
            port - int port to connect to
        """
        self.host = host
        self.remote_port = int(port)
        self.log("Sender starting up using port %s" % self.remote_port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.waiting = False
        self.sequence_number = 0
        self.current_window_size = 0
        self.max_window_size = 12
        self.ssthres = 32
        # { Sequence number: bool representing whether we have recieved an ack for that sequence number }
        # Needs to be seperate from message cache for duplication detection
        self.sequence_num_to_ack = {}
        # { Sequence number: (message json, time message was last sent, bool representing if packet has been retransmitted) }
        # Corresponds to data we need to keep track of before we recieve an ACK for said packet
        self.message_cache = {}
        # round trip time initializes at 1 second
        self.rtt = 1
        # time to timeout initializes at 2 * RTT seconds
        self.rto = 2

    def log(self, message):
        sys.stderr.write(str(message) + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % message)
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.host, self.remote_port))

    def decrease_current_window_size(self):
        # We recieved an ack back, so we know reciever recieved message, so take it out of our window
        # effectively making our window size smaller by 1
        self.current_window_size -= 1

    def increase_current_window_size(self):
        # We send a message out, so we have another message in our network, so increase window size by 1
        self.current_window_size += 1

    def update_waiting_status(self):
        # if our window size is under max, we must have recieved an ack, so slide window forward so we can send another
        if self.current_window_size < self.max_window_size:
            self.waiting = False
        # otherwise our current window size is equal to or above or max, so wait
        else:
            self.waiting = True

    def ack_has_all_attributes(self, ack):
    # checks ack has required fields to be valid
        return 'type' in ack and 'num' in ack and 'checksum' in ack

    def ack_has_proper_checksum(self, ack):
    # checks ack has acceptable checksum to be valid
        cksum_rec = ack['checksum']
        ack.pop('checksum')
        cksum_calc = zlib.crc32(json.dumps(ack).encode('utf-8'))
        return cksum_rec == cksum_calc

    # multiplicative decrease for ssthres, drop max window size to 1
    def decrease_ssthres_and_max_window_size(self):
        self.ssthres = self.max_window_size / 2
        self.max_window_size = 1

    # increase max window/congestion window size since we recieved a new ack
    def increase_max_window_size(self):
        if self.max_window_size < self.ssthres:
            self.max_window_size += 1
        else:
            self.max_window_size += (1 / self.max_window_size)
        
    def is_duplicate_ack(self, ack):
        return self.sequence_num_to_ack[ack['num']]

    def has_been_retransmitted(self, sequence_num):
        return self.message_cache[sequence_num][2]

    def update_rtt_and_rto(self, sequence_num):
        self.rtt = (.875 * self.rtt) + (.125 * (datetime.now() - self.message_cache[sequence_num][1]).total_seconds())
        self.rto = 2 * self.rtt

    def run(self):
        while True:
            sockets = [self.socket, sys.stdin] if not self.waiting else [self.socket]

            socks = select.select(sockets, [], [], 0.1)[0]
            for sequence_num, (msg, time, retransmitted) in self.message_cache.items():
                # if we haven't recieved an ack and it has been longer than the time to wait (which is 2x the rtt)
                if not self.sequence_num_to_ack[sequence_num] and (datetime.now() - time).total_seconds() > self.rto:
                    #self.log("Max window size: %d , Current window size: %d " % (self.max_window_size, self.current_window_size))
                    self.send(msg)
                    # Update last sent time in message cache & flag it as being retransmitted so we can ignore it in RTT calculations
                    self.message_cache[sequence_num] = (msg, datetime.now(), True)
                    # We know a packet got dropped, so do multiplicative decrease for ssthres and drop max window size to 1
                    self.decrease_ssthres_and_max_window_size()
          
            for conn in socks:
                # get message sent from sender's socket
                if conn == self.socket:
                    k, addr = conn.recvfrom(65535)
                    try:
                        msg = json.loads(k.decode('utf-8'))
                    except:
                        # corrupted packet
                        continue

                    self.log("Received message '%s'" % msg)
                    
                    # Corrupted message check
                    if not (self.ack_has_all_attributes(msg) and self.ack_has_proper_checksum(msg)):
                        self.log("Ignoring message due to corruption '%s'" % msg)
                        continue
                    
                    # If this is a duplicate ack, don't mess with window size or waiting status and just continue to next
                    if self.is_duplicate_ack(msg):
                        self.log("Ignoring message due to duplication '%s'" % msg)
                        continue

                    # update window size and waiting status according to msg
                    self.decrease_current_window_size()
                    self.update_waiting_status()

                    # To signify that we have recieved an ack for this sequence number
                    self.sequence_num_to_ack[msg["num"]] = True
                    
                    # recieved new ack, update congestion window
                    self.increase_max_window_size()
    
                    # Only do rtt and rto calculations if it is a packet which hasn't been retransmitted            
                    if not self.has_been_retransmitted(msg['num']):
                        self.update_rtt_and_rto(msg['num'])
                        #self.log("max window size {}".format(self.max_window_size))
                        #self.log("ssthres is {}".format(self.ssthres))

                    # Delete corresponding message from message cache since we got a valid ack for it 
                    self.message_cache.pop(msg['num'])

                elif conn == sys.stdin:
                    data = sys.stdin.read(DATA_SIZE)
                    # don't exit unless we have recieved an ACK back for every packet we have sent
                    if len(data) == 0 and self.current_window_size == 0:
                        self.log("All done!")
                        sys.exit(0)
                    # If no more data to send but haven't recieved ack back for everything, just continue
                    elif len(data) == 0:
                        continue
                
                    self.sequence_number = self.sequence_number + 1
                    msg = { "type": "msg", "data": data, "sequence_number": self.sequence_number }
                    # Add checksum field for crc 32bit integer checksum calculated over whole packet
                    # (obviously excluding checksum field)
                    msg['checksum'] = zlib.crc32(json.dumps(msg).encode('utf-8'))
                    # Add to message cache which is all the info we care about until it has been ACKed
                    # contains (message json, time message was last sent, bool representing if packet has been retransmitted)
                    self.message_cache[msg['sequence_number']] = (msg, datetime.now(), False)
                    self.send(msg)
                    self.increase_current_window_size()
                    self.update_waiting_status()
                    self.sequence_num_to_ack[self.sequence_number] = False
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
